// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Seequent.Infrastructure;

[Table("Borehole")]
public partial class Borehole
{
    [Key]
    public long Id { get; set; }

    public int DepthKm { get; set; }

    public int XLocationKm { get; set; }

    public int YLocationKm { get; set; }

    [StringLength(100)]
    public string CableType { get; set; }

    [StringLength(500)]
    public string CableStrength { get; set; }

    [StringLength(100)]
    public string DrillType { get; set; }

    [StringLength(500)]
    public string DrillStrength { get; set; }
}