// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Seequent.Core;

namespace Seequent.Infrastructure;

public partial class SeequentDbContext : DbContext
{
    public SeequentDbContext(DbContextOptions<SeequentDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Borehole> Boreholes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}